version: 0.2

env:
  variables:
    VAR_Owner: Elendel

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install all the test packages
      - apt update
      - apt install -y wget zip jq
      - pip install --upgrade pip
      - pip install --upgrade setuptools
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - pip install pipenv
      - pipenv lock --clear
      - pipenv lock -r --dev > requirements_test.txt
      - pip install -r requirements_test.txt
    finally:
      - printenv

  pre_build:  
    commands:
      - PYTHONPATH=src/layers/python/:$PYTHONPATH pipenv run pytest --cov=src -vv --cov-report term-missing
      - flake8 --ignore=E501,E402 ./src
      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
        
  build:
    commands:
      - pipenv lock -r > requirements.txt
      - sam build -t .sam/template.yaml -m ./requirements.txt -b ./build -s .
