AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Days ANZ 2020 Demo
Parameters:
  Environment:
    Type: String
    Default: dev
  GitHash:
    Type: String
    Default: latest
  APIDomainName:
    Type: String
    Default: serverlessdays.elendel.com.au
  Certificate:
    Type: String
    Default: arn:aws:acm:us-east-1:801604450668:certificate/30ada2b1-e581-4379-a0e5-4bf3cbad7bb4
  HostedZoneId:
    Type: String
    Default: Z18PP28MZC4N6M
  HostedZoneName:
    Type: String
    Default: elendel.com.au
  DynamoDBStackImport:
    Type: String
    Default: ServerlessDaysANZ-Demo-DynamoDB-DynamoDB-PDFTable
  S3StackImport:
    Type: String
    Default: ServerlessDaysANZ-Demo-S3-S3-Bucket
  KMSStackImport:
    Type: String
    Default: ServerlessDaysANZ-Demo-S3-KMS-Key-Arn
  Logging:
    Type: String
    Default: DEBUG

Globals:
  Function:
    Runtime: python3.8
    Timeout: 60
    Handler: app.lambda_handler
    Tracing: Active
    Environment:
      Variables:
        Logging: !Ref Logging
        Bucket: 
          Fn::ImportValue:
            !Sub "${S3StackImport}"
        KMSKey: 
          Fn::ImportValue:
            !Sub "${KMSStackImport}"
        Table: 
          Fn::ImportValue:
            !Sub "${DynamoDBStackImport}"

Resources:

  Gateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "ServerlessDays Demo API Gateway ${Environment} ${GitHash}"
      StageName: !Ref Environment
      BinaryMediaTypes:
      - "application~1pdf"

  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref Certificate
      DomainName: !Sub "${GitHash}.${APIDomainName}"

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref Gateway
      Stage: !Ref Environment

  Route53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Type: A
        Name: !Sub "${GitHash}.${APIDomainName}"
        AliasTarget:
          HostedZoneId: !GetAtt DomainName.DistributionHostedZoneId
          DNSName: !GetAtt DomainName.DistributionDomainName

  ############ Layers  ############

  DemoCoreLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: !Sub "CoreLayer-${GitHash}"
        Description: Core classes and objects for Serverless Day Demo 
        ContentUri: ../src/layers
        CompatibleRuntimes:
          - python3.7
          - python3.8
        LicenseInfo: 'MIT'
        RetentionPolicy: Retain

  ############ /create_pdf ############

  CreatePDF:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/create_pdf
      FunctionName: !Sub "CreatePDF_${GitHash}"
      Layers:
        - !Ref DemoCoreLayer
      Events:
        post:
          Type: Api
          Properties:
            RestApiId: !Ref Gateway
            Path: /create_pdf
            Method: POST
      Role: !GetAtt CreatePDFExecutionRole.Arn

  CreatePDFExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: create_pdf
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:*'
                  - 's3:ListBucket'
                  - 's3:ListBucket*'
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                  - 'kms:encrypt'
                  - 'kms:DescribeKey'
                  - 'kms:GenerateDataKey'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:PutItem'
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                Resource: '*'

  ############ /delete_pdf ############

  DeletePDF:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/delete_pdf
      FunctionName: !Sub "DeletePDF_${GitHash}"
      Layers:
        - !Ref DemoCoreLayer
      Events:
        post:
          Type: Api
          Properties:
            RestApiId: !Ref Gateway
            Path: /delete_pdf/{DocId}
            Method: DELETE
      Role: !GetAtt DeletePDFExecutionRole.Arn

  DeletePDFExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: delete_pdf
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:*'
                  - 's3:ListBucket'
                  - 's3:ListBucket*'
                  - 's3:DeleteObject'
                  - 's3:DeleteObjectVersion'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:Query'
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                Resource: '*'

  ############ /get_pdf ############

  GetPDF:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/get_pdf
      FunctionName: !Sub "GetPDF_${GitHash}"
      Layers:
        - !Ref DemoCoreLayer
      Events:
        post:
          Type: Api
          Properties:
            RestApiId: !Ref Gateway
            Path: /get_pdf/{DocId}
            Method: GET
      Role: !GetAtt GetPDFExecutionRole.Arn

  GetPDFExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: get_pdf
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:*'
                  - 's3:ListBucket'
                  - 's3:ListBucket*'
                  - 's3:GetObject'
                  - 's3:GetObject*'
                  - 'kms:decrypt'
                  - 'kms:DescribeKey'
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                Resource: '*'

  ############ /list_pdf ############

  ListPDF:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/list_pdf
      FunctionName: !Sub "ListPDF_${GitHash}"
      Layers:
      - !Ref DemoCoreLayer
      Events:
        post:
          Type: Api
          Properties:
            RestApiId: !Ref Gateway
            Path: /list_pdf
            Method: GET
      Role: !GetAtt ListPDFExecutionRole.Arn

  ListPDFExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: list_pdf
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:*'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:ListTables'
                  - 'dynamodb:Scan'
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                Resource: '*'